# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OkctlAT0_0_6 < Formula
  desc "Opinionated and effortless infrastructure and application management"
  homepage "https://github.com/oslokommune/okctl"
  version "0.0.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/oslokommune/goreleaser-test/releases/download/v0.0.6/okctl_Darwin_amd64.tar.gz"
      sha256 "62f3ef0f0d21f7d3108d7d96de7ab7535ec195b8b580fe9056c9883d67bebde2"

      def install
        bin.install "goreleaser-test"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/oslokommune/goreleaser-test/releases/download/v0.0.6/okctl_Linux_amd64.tar.gz"
      sha256 "c5acd470166c8b0c1b169e4b3df2a37f16168da185735bd75743a8ff31abbd5b"

      def install
        bin.install "goreleaser-test"
      end
    end
  end

  head "https://github.com/oslokommune/goreleaser-test/releases/download/latest_release/goreleaser-test_Darwin_amd64.tar.gz"
end
